spring:
  jpa:
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.autorabit.rabbiturl: INFO
    org.apache.kafka: WARN
    org.hibernate: WARN
